[project]
name = "b3cotahist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "polars>=1.12.0",
    "requests>=2.32.3",
]

[tool.poetry]
name = "b3cotahist"
version = "0.1.10"
description = "Uma biblioteca simples para facilitar a leitura e o parsing do arquivo COTAHIST da B3."
authors = ["renanmoretto <himynameisrenan@outlook.com>"]
readme = "README.md"
repository = "https://github.com/renanmoretto/b3cotahist"

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
]
